### PR TITLE
fix(exports): correctly generate export paths for nested index files

### LINKED ISSUE #558: export true doesn't normalize subpackages exports paths on Windows
### Reproduction link or steps

Add a subpackage export on Windows laptop enabling `export: true` in the `tsdown.config.ts` file:

screenshot using \ in the subpackage exports

debug generateExports screenshot

 

### What is expected?

Subpackage exports should use `/` instead separator path

### What is actually happening?

Using separator path, requires applying a normalization

### Any additional comments?

I'm going to send a PR to fix this bug.

In fact the generated subpackages exports are wrong: we need to handle multiple entries and group them: check core/types and core/index, maybe a side effect of this issue (?)

### PR DESCRIPTION
**Pull request by userquin**
### Description

This fix normalizes entrypoint paths to correctly handle subpackage exports, especially for nested index files and paths generated on Windows.

### Linked Issues

resolves #558

### Additional context

~~After updating my fork, on my local there are 3/4 tests failing: env and shims related to define/inject changes at Rolldown~~

### CODE REVIEW

File: src/features/exports.ts [hunk 1]
```diff
@@ -111,20 +111,21 @@ export async function generateExports(
         (chunk) =>
           chunk.type === 'chunk' &&
           chunk.isEntry &&
-          !RE_DTS.test(chunk.fileName),
+          !RE_DTS.test(slash(chunk.fileName)),
```
Comment (sxzz) [inline src/features/exports.ts]: This line can be reverted, since suffix name is the same in both Windows and Linux.

File: src/features/exports.ts [hunk 2]
```diff
@@ -111,20 +111,21 @@ export async function generateExports(
...
       ).length === 1
     for (const chunk of chunksByFormat) {
       if (chunk.type !== 'chunk' || !chunk.isEntry) continue
 
-      const ext = path.extname(chunk.fileName)
-      let name = chunk.fileName.slice(0, -ext.length)
+      const normalizedName = slash(chunk.fileName)
+      const ext = path.extname(normalizedName)
+      let name = normalizedName.slice(0, -ext.length)
```
Comment (sxzz) [inline src/features/exports.ts:121]: Same here?

File: src/features/exports.ts [hunk 3]
```diff
@@ -111,20 +111,21 @@ export async function generateExports(
...
 
       const isDts = name.endsWith('.d')
       if (isDts) {
         name = name.slice(0, -2)
       }
       const isIndex = onlyOneEntry || name === 'index'
-      const distFile = `${outDirRelative ? `./${outDirRelative}` : '.'}/${chunk.fileName}`
+      const distFile = `${outDirRelative ? `./${outDirRelative}` : '.'}/${normalizedName}`
```
Comment (sxzz) [inline src/features/exports.ts:128]: Seems like only here needs be normalized.

Comment (userquin) [reply src/features/exports.ts:128]: Will apply changes tmr

File: src/features/exports.ts (hunk 2 above)
Comment (userquin) [reply src/features/exports.ts:121]: uhmmm, at L120, using chunk.fileName at L121 error:

error applying suggestion
